# Generated by Django 4.0.6 on 2022-08-04 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='vaga',
            name='descricao_vaga',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='qtd_vagas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='escolaridade',
            field=models.CharField(max_length=40),
        ),
    ]
