# Generated by Django 4.0.6 on 2022-08-04 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidatos', '0003_candidato_email_candidato_nome_candidato'),
        ('vagas', '0002_vaga_date_vaga_descricao_vaga_vaga_qtd_vagas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='candidato',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='pessoa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
