# Generated by Django 4.0.6 on 2022-08-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_vaga_candidato_vaga_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='candidato',
        ),
    ]
