# Generated by Django 4.0.6 on 2022-08-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_remove_vaga_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='inscritos_na_vaga',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
