# Generated by Django 4.0.6 on 2022-08-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_vaga_inscritos_na_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='qtd_inscritos',
            field=models.IntegerField(default=0),
        ),
    ]
