# Generated by Django 4.0.6 on 2022-08-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0006_vaga_qtd_inscritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='inscritos_na_vaga',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
