# Generated by Django 4.0.6 on 2022-08-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0008_alter_vaga_inscritos_na_vaga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='inscritos_na_vaga',
        ),
    ]
