# Generated by Django 4.0.6 on 2022-08-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0013_alter_vaga_faixa_salarial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='escolaridade',
            field=models.CharField(choices=[('Ensino fundamental', 'Ensino fundamental'), ('Ensino médio', 'Ensino médio'), ('Tecnólogo', 'Tecnólogo'), ('Ensino Superior', 'Ensino Superior'), ('Pós / MBA / Mestrado', 'Pós / MBA / Mestrado'), ('Doutorado', 'Doutorado')], max_length=40),
        ),
    ]
