# Generated by Django 4.0.6 on 2022-08-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('cnpj', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=40)),
            ],
        ),
    ]
