# Generated by Django 4.0.6 on 2022-08-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo_usuario',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
