# Generated by Django 4.0.6 on 2022-08-01 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_empresa_pessoa_usuario_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pessoa',
        ),
    ]
