# Generated by Django 4.0.6 on 2022-08-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_empresa_pessoa_usuario_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
