# Generated by Django 4.0.6 on 2022-08-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0006_vaga_qtd_inscritos'),
        ('candidatos', '0003_candidato_email_candidato_nome_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='candidato_vaga',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga'),
            preserve_default=False,
        ),
    ]
