# Generated by Django 4.0.6 on 2022-08-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0004_candidato_candidato_vaga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='experiancia',
            new_name='experiencia',
        ),
    ]
